project:
  type: website
  output-dir: docs

website:
  title: "Medical Maths"
  favicon: favicon.png
  search: false
  navbar:
    background: "#007ba8"
    foreground: "#ffffff"
    logo: logo.png
    pinned: true
    right:
      - about.qmd
      - text: Home
        href: index.qmd
      # - icon: bi-envelope
      #  href: mailto:medmaths@protonmail.com
      # - icon: github
      #  href: https://github.com/medmaths
    
date-format: long
language: 
  section-title-footnotes: "References" 
appendix-style: plain
tbl-cap-location: bottom
    
format:
  html:
    css: medmaths-custom-styling.css
    theme:
      - default
      - medmaths-custom-theme.scss
    html-math-method:
      method: mathjax
      # url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
      # method: katex
    code-overflow: scroll
    code-copy: false
    highlight-style: pygments