{
  "hash": "fc8952c3ca453494ba33cff9a177091c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Evidence Synthesis and Forest Plots\"\ndate: \"2025-02-18\"\nimage: thumbnail.png\n---\n\n\n::: {.callout-warning}\n## Disclaimer\nThis blog post was written solely for informational and educational purposes, and does not constitute medical advice. If you have any health concerns, please consult a qualified medical professional.\n:::\n\nMeta-analyses and the forest plots they produce are important tools in helping researchers to combine evidence from multiple different studies. In this article, I’ll work through the steps of a fixed-effect meta-analysis, using data from an early and influential systematic review.\n\n## Antenatal Steroids\n\nIn 1972, an obstetrican and neonatologist working at the National Women's Hospital in Auckland, New Zealand, published the initial findings from a randomised contolled trial they had begun in 1969[^1]. Once all the results were in, this trial showed a significant reduction in the mortality of premature babies whose mothers had been given antenatal steroids, compared to those whose mothers had not received this treatment. \n\nHowever, one unreplicated trial rarely provides enough evidence for medical practice to change drastically. Over the following decade, another seven, smaller, RCTs of this treatment were carried out, but only two of them showed an effect that was [statistically significant](https://en.wikipedia.org/wiki/Statistical_significance) at a significance level of 5%. It took a later meta-analysis to show that, when combined, the first eight RCTs of antenatal steroids were in fact sufficient to show a significant effect of antenatal steroids on neonatal mortality in premature babies[^2].\n\nThe results of all eight of these studies can be found in a Cochrane review from 1996[^3].\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Inputting the Results of the Eight RCTs into a Data Frame in R\"}\nsteroid_trials <- data.frame(\n  control_group_size = c(538, 61, 59, 75, 58, 71, 63, 372), \n  control_group_deaths = c(60, 5, 7, 7, 12, 10, 11, 34), \n  treatment_group_size = c(532, 69, 67, 71, 64, 56, 81, 371), \n  treatment_group_deaths = c(36, 1, 3, 1, 3, 8, 4, 32))\n\ntrial_names <- c(\"Liggins and Howie (1972)\",\n                 \"Block et al. (1977)\",\n                 \"Morrison et al. (1978)\",\n                 \"Papageorgiou et al. (1979)\",\n                 \"Schutte et al. (1979)\",\n                 \"Taeusch et al. (1979)\",\n                 \"Doran et al. (1980)\",\n                 \"Collaborative Group (1981)\")\n\nrownames(steroid_trials) <- trial_names\n\nnum_trials <- nrow(steroid_trials)\n\ntotals <- rep(NA, times=num_trials)\nfor (i in 1:num_trials) {\n  totals[i] <- steroid_trials$control_group_size[i] +  steroid_trials$treatment_group_size[i]\n}\nsteroid_trials$total_trial_size <- totals\n```\n:::\n\n```{=html}\n<div style=\"overflow-x:auto;\">\n  <table class=\"table table-bordered table-sm\">\n      <caption>The Results of the First Eight Randomised Controlled Trials of the Effect of Antenatal Steroids on Neonatal Mortality in Premature Babies</caption>\n      <tr>\n          <td colspan=\"2\" rowspan=\"2\" style=\"background-color: #e4f8ff\"></td>\n          <td colspan=\"2\" style=\"text-align: center; vertical-align: middle; background-color: #006a90; color: white;\">Control Group</td>\n          <td colspan=\"2\" style=\"text-align: center; vertical-align: middle; background-color: #006a90; color: white;\">Treatment Group</td>\n          <td rowspan=\"2\" style=\"text-align: center; vertical-align: middle; background-color: #006a90; color: white;\">Total <div style=\"white-space: nowrap;\">Number of </div>Babies in the Study</td>\n      </tr>\n      <tr>\n        <td style=\"text-align: center; vertical-align: middle; background-color: #009ed8; color: white;\"><div style=\"white-space: nowrap;\">Number of </div><div style=\"white-space: nowrap;\">Babies in the </div>Group</td>\n        <td style=\"text-align: center; vertical-align: middle; background-color: #009ed8; color: white;\"><div style=\"white-space: nowrap;\">Number of </div>Neonatal Deaths</td>\n        <td style=\"text-align: center; vertical-align: middle; background-color: #009ed8; color: white;\"><div style=\"white-space: nowrap;\">Number of </div><div style=\"white-space: nowrap;\">Babies in the </div>Group</td>\n        <td style=\"text-align: center; vertical-align: middle; background-color: #009ed8; color: white;\"><div style=\"white-space: nowrap;\">Number of </div>Neonatal Deaths</td>\n      </tr>\n      <tr>\n          <td rowspan=\"8\" style=\"text-align: center; vertical-align: middle; background-color: #006a90; color: white;\">Randomised Control Trial</td>\n          <td style=\"text-align: center; vertical-align: middle; background-color: #009ed8; color: white;\"><div style=\"white-space: nowrap;\">Liggins and Howie </div>(1972)</td>\n          <td style=\"text-align: center; vertical-align: middle;\">538</td>\n          <td style=\"text-align: center; vertical-align: middle;\">60</td>\n          <td style=\"text-align: center; vertical-align: middle;\">532</td>\n          <td style=\"text-align: center; vertical-align: middle;\">36</td>\n          <td style=\"text-align: center; vertical-align: middle;\">1070</td>\n      </tr>\n      <tr>\n          <td style=\"text-align: center; vertical-align: middle; background-color: #009ed8; color: white;\"><div style=\"white-space: nowrap;\">Block et al. </div>(1977)</td>\n          <td style=\"text-align: center; vertical-align: middle;\">61</td>\n          <td style=\"text-align: center; vertical-align: middle;\">5</td>\n          <td style=\"text-align: center; vertical-align: middle;\">69</td>\n          <td style=\"text-align: center; vertical-align: middle;\">1</td>\n          <td style=\"text-align: center; vertical-align: middle;\">130</td>\n      </tr>\n      <tr>\n          <td style=\"text-align: center; vertical-align: middle; background-color: #009ed8; color: white;\"><div style=\"white-space: nowrap;\">Morrison et al. </div>(1978)</td>\n          <td style=\"text-align: center; vertical-align: middle;\">59</td>\n          <td style=\"text-align: center; vertical-align: middle;\">7</td>\n          <td style=\"text-align: center; vertical-align: middle;\">67</td>\n          <td style=\"text-align: center; vertical-align: middle;\">3</td>\n          <td style=\"text-align: center; vertical-align: middle;\">126</td>\n      </tr>\n      <tr>\n          <td style=\"text-align: center; vertical-align: middle; background-color: #009ed8; color: white;\"><div style=\"white-space: nowrap;\">Papageorgiou et al. </div>(1979)</td>\n          <td style=\"text-align: center; vertical-align: middle;\">75</td>\n          <td style=\"text-align: center; vertical-align: middle;\">7</td>\n          <td style=\"text-align: center; vertical-align: middle;\">71</td>\n          <td style=\"text-align: center; vertical-align: middle;\">1</td>\n          <td style=\"text-align: center; vertical-align: middle;\">146</td>\n      </tr> \n      <tr>\n          <td style=\"text-align: center; vertical-align: middle; background-color: #009ed8; color: white;\"><div style=\"white-space: nowrap;\">Schutte et al. </div>(1979)</td>\n          <td style=\"text-align: center; vertical-align: middle;\">58</td>\n          <td style=\"text-align: center; vertical-align: middle;\">12</td>\n          <td style=\"text-align: center; vertical-align: middle;\">64</td>\n          <td style=\"text-align: center; vertical-align: middle;\">3</td>\n          <td style=\"text-align: center; vertical-align: middle;\">122</td>\n      </tr> \n      <tr>\n          <td style=\"text-align: center; vertical-align: middle; background-color: #009ed8; color: white;\"><div style=\"white-space: nowrap;\">Taeusch et al. </div>(1979)</td>\n          <td style=\"text-align: center; vertical-align: middle;\">71</td>\n          <td style=\"text-align: center; vertical-align: middle;\">10</td>\n          <td style=\"text-align: center; vertical-align: middle;\">56</td>\n          <td style=\"text-align: center; vertical-align: middle;\">8</td>\n          <td style=\"text-align: center; vertical-align: middle;\">127</td>\n      </tr> \n      <tr>\n          <td style=\"text-align: center; vertical-align: middle; background-color: #009ed8; color: white;\"><div style=\"white-space: nowrap;\">Doran et al. </div>(1980)</td>\n          <td style=\"text-align: center; vertical-align: middle;\">63</td>\n          <td style=\"text-align: center; vertical-align: middle;\">11</td>\n          <td style=\"text-align: center; vertical-align: middle;\">81</td>\n          <td style=\"text-align: center; vertical-align: middle;\">4</td>\n          <td style=\"text-align: center; vertical-align: middle;\">144</td>\n      </tr> \n      <tr>\n          <td style=\"text-align: center; vertical-align: middle; background-color: #009ed8; color: white;\"><div style=\"white-space: nowrap;\">Collaborative Group </div>(1981)</td>\n          <td style=\"text-align: center; vertical-align: middle;\">372</td>\n          <td style=\"text-align: center; vertical-align: middle;\">34</td>\n          <td style=\"text-align: center; vertical-align: middle;\">371</td>\n          <td style=\"text-align: center; vertical-align: middle;\">32</td>\n          <td style=\"text-align: center; vertical-align: middle;\">743</td>\n      </tr> \n  </table>\n</div>\n```\n\n\n\nHere, the years in parentheses after the authors' names are the years of publication of the first papers they disseminated relating to their trials.\n\n## The Individual Trials’ Findings\n\nOnce all the eligible trials have been identified and assessed for bias, the first step of any meta-analysis is to estimate a treatment effect from each of them.\n\nIn this article, we will use the **risk ratio** as a measure of the treatment effect. This is a common measure of the association between an exposure and an event, and is equal to the probability of the event in the exposed group divided by the probability of the event in the non exposed group. \n\nFor example, suppose that a trial produces the following [contingency table](https://en.wikipedia.org/wiki/Contingency_table). \n\n\n\n```{=html}\n<div style=\"overflow-x:auto;\">\n  <table class=\"table table-bordered table-sm\">\n      <caption>Example Contingency Table</caption>\n      <tr>\n        <td style=\"background-color: #e4f8ff\"></td>\n        <td style=\"text-align: center; vertical-align: middle; background-color: #006a90; color: white;\">Exposed Group</td><td style=\"text-align: center; vertical-align: middle; background-color: #006a90; color: white;\">Non-Exposed Group</td>\n      </tr>\n      <tr>\n         <td style=\"text-align: center; vertical-align: middle; background-color: #006a90; color: white;\">Number of Events</td>\n         <td style=\"text-align: center; vertical-align: middle;\">\n         <math>\n            <mi>a</mi>\n         </math>\n         </td><td style=\"text-align: center; vertical-align: middle;\">\n         <math>\n          <mi>c</mi>\n         </math>\n         </td>\n      </tr>\n      <tr>\n        <td style=\"text-align: center; vertical-align: middle; background-color: #006a90; color: white;\">Number of Non-Events </td>\n        <td style=\"text-align: center; vertical-align: middle;\">\n        <math>\n          <mi>b</mi>\n        </math>\n      </td>\n      <td style=\"text-align: center; vertical-align: middle;\">\n         <math>\n          <mi>d</mi>\n         </math>      \n      </td>\n    </tr>\n  </table>\n</div>\n```\n\n\n\nThen we can find an estimate for the risk ratio using the formula[^4] \n\n$$\n\\widehat{\\text{RR}}=\\frac{a}{a+b}\\div\\frac{c}{c+d}.\n$$\n\nA risk ratio of $1$ indicates that there is no difference in the probability of the event occurring in the exposed group and the probability of the event occurring in the non-exposed group. Risk ratios are usually plotted on a logarithmic scales in forest plots, so that a change in risk ratio representing a doubling in risk appears equal to a change in risk ratio representing a halving of risk[^5]. \n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Calculating and Plotting the Risk Ratios in R\"}\nrisk_ratios <- rep(NA, times=num_trials)\nfor (i in 1:num_trials) {\n  treatment_incidence <- steroid_trials$treatment_group_deaths[i]/steroid_trials$treatment_group_size[i]\n  control_incidence <- steroid_trials$control_group_deaths[i]/steroid_trials$control_group_size[i]\n  risk_ratios[i] <- treatment_incidence/control_incidence\n}\nsteroid_trials$risk_ratio <- risk_ratios\n\nempty_forest_plot <- function (xax, yax) {\n  plot(1, type=\"n\", log = \"x\", \n     cex.lab=1.5, cex.axis=1.5,\n     xlim=xax, xlab=\"Risk Ratio\", \n     ylim=yax, ylab=\" \", frame.plot = FALSE, yaxt=\"n\")\n  yline <- yax + c(-0.5, 0.5)\n  segments(1, yax[1], 1, yax[2])\n  for (i in 1:num_trials) {\n    y_coord <- num_trials+1-i\n    text(3, y_coord, adj=0, trial_names[i], cex=1.2)\n  }\n}\n\npar(mar=c(bottom=4.2, left=5.1, top=0, right=0.9), family=\"Roboto Slab\") # setting the plot options\nempty_forest_plot(xax=c(0.1, 10), yax=c(0.5, 8.5))\npoints(steroid_trials$risk_ratio, 8:1, \n       pch=4, col=\"#006a90\", cex=1.8, lwd=4.2)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/risk-ratios-1.png){width=1152}\n:::\n:::\n\n\n\nThese point estimates for the risk ratio are not actually very useful on their own, because they do not give information about the different levels of uncertainty surrounding each estimate. For instance, we can tell intuitively that the estimate we found from the study of 1070 babies is likely to be less reliable than the estimate we found from the study of 127 babies.\n\nTo solve this problem, we can calculate approximate 95% confidence intervals for each study, using the fact that the natural logarithm of our estimator of the risk ratio [converges in distribution](https://en.wikipedia.org/wiki/Convergence_of_random_variables#Convergence_in_distribution) to a normal distribution with a mean of zero, and a standard deviation that we can approximate using the formula[^6]\n\n$$\n\\widehat{\\text{SD}}_{\\text{log}\\widehat{\\text{RR}}}=\\sqrt{n}\\cdot\\text{SE}_{\\text{log}\\widehat{\\text{RR}}}=\\sqrt{n}\\left(\\sqrt{\\frac{1}{a}-\\frac{1}{a+b}+\\frac{1}{c}+\\frac{1}{c+d}}\\right),\n$$\nwhere $a$, $b$, $c$, and $d$ again represent the counts in the contingency table.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Estimating and Plotting the Confidence Intervals in R\"}\nconfidence_intervals <- data.frame(\n  lower = rep(NA, times=num_trials),\n  upper = rep(NA, times=num_trials)\n)\nalpha <- 0.05\nz_val <- qnorm(1-alpha/2)\nfor (i in 1:num_trials) {\n  log_rr <- log(steroid_trials$risk_ratio[i])\n  log_rr_SE <- sqrt((1/steroid_trials$control_group_deaths[i]) + (1/steroid_trials$treatment_group_deaths[i])\n                     - (1/steroid_trials$control_group_size[i]) - (1/steroid_trials$treatment_group_size[i]))\n  log_lower <- log_rr - z_val * log_rr_SE\n  log_upper <- log_rr + z_val * log_rr_SE\n  confidence_intervals$lower[i] <- exp(log_lower)\n  confidence_intervals$upper[i] <- exp(log_upper)\n}\n\npar(mar=c(bottom=4.2, left=5.1, top=0, right=0.9), family=\"Roboto Slab\")\nempty_forest_plot(xax=c(0.1, 10), yax=c(0.5, 8.5))\n\nplot_CIs <- function(CIs_df) {\n  num_CIs <- nrow(CIs_df)\n  for (i in 1:num_CIs){\n    y_coord <- num_CIs+1-i\n    lower <- CIs_df$lower[i]\n    upper <- CIs_df$upper[i]\n    if (lower < 0.1) {\n      arrows(x0=0.1, y0=y_coord, \n             x1=upper, y1=y_coord, \n             code=1, length=0.18,\n             lwd=4.2, col=\"#009ed8\")      \n    } else {\n      segments(x0=lower, y0=y_coord, \n               x1=upper, y1=y_coord,\n               lwd=4.2, col=\"#009ed8\")\n    }\n  }\n}\n\nplot_CIs(confidence_intervals)\npoints(steroid_trials$risk_ratio, 8:1, \n       pch=4, col=\"#006a90\", cex=1.8, lwd=4.2)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/confidence-intervals-1.png){width=1152}\n:::\n:::\n\n\n\n## Pooling the Results\n\nNow we want to combine these estimates, giving more weight to the those with lower variance. One way to do this would be to give each estimate a weight proportional to the inverse an estimate of its variance, which we could calculate using our previously estimated standard deviation of the log risk ratio. However, this method can be unreliable when the study size is small or the probability of the event we are studying is rare, which is why the Cochrane Collaboration recommends that researchers use the **Mantel-Haenszel** method for pooling estimates instead[^7].\n\nIn this method, each estimate, $\\widehat{\\text{RR}}_i$, is given a weight of[^8]\n\n$$\nw_i=\\frac{(a_i+b_i)c_i}{a_i+b_i+c_i+d_i},\n$$\n\nwhere for each trial $a_i$ and $b_i$ are the numbers of events and non-events in the exposed group, and $c_i$ and $d_i$ are the numbers of the events and non-events in the non-exposed group. The Mantel-Haenszel estimate is then equal to \n\n$$\n\\widehat{\\text{RR}}_{\\text{M-H}}=\\frac{\\sum w_i \\widehat{\\text{RR}}_i}{\\sum w_i}.\n$$\n\nWe can find an approximate confidence interval for the Mantel-Haenszel estimator using the asmpymptotic normality of its natural logarithm. A formula for its approximate standard error is given in [this guide](https://imaging.mrc-cbu.cam.ac.uk/statswiki/FAQ/meta?action=AttachFile&do=get&target=cochraneor.pdf) to standard statistical algorithms used in Cochrane reviews.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Calculating a Mantel-Haenszel Pooled Estimate and Confidence Interval for the First Eight Antenatal Steroid RCTs in R\"}\nweights <- rep(NA, num_trials)\nfor (i in 1:num_trials) {\n  treatment_events <- steroid_trials$treatment_group_deaths[i]\n  treatment_non_events <- steroid_trials$treatment_group_size[i] - treatment_events\n  control_events <- steroid_trials$control_group_deaths[i]\n  sample_size <- steroid_trials$total_trial_size[i]\n  weights[i] <- (treatment_events + treatment_non_events) * control_events / sample_size\n}\nsteroid_trials$normalised_weight <- weights / sum(weights)\npooled_rr_estimate <- sum(steroid_trials$risk_ratio * steroid_trials$normalised_weight)\n\n# We find the standard error using the formula from this guide by Jon Deeks and Julian Higgins:\n# https://imaging.mrc-cbu.cam.ac.uk/statswiki/FAQ/meta?action=AttachFile&do=get&target=cochraneor.pdf\nn_1 <- steroid_trials$treatment_group_size\nn_2 <- steroid_trials$control_group_size\na <- steroid_trials$treatment_group_deaths\nc <- steroid_trials$control_group_deaths\nN <- steroid_trials$total_trial_size\nP <- sum((n_1*n_2*(a+c)-a*c*N)/N^2) \nR <- sum(a*n_2/N)\nS <- sum(c*n_1/N)\nlog_SE <- sqrt(P/(R*S))\n\nalpha <- 0.05\nz_val <- qnorm(1-alpha/2)\nlog_CI_lower <- log(pooled_rr_estimate) - z_val * log_SE\nlog_CI_upper <- log(pooled_rr_estimate) + z_val * log_SE\nCI <- exp(c(log_CI_lower, log_CI_upper))\ncat(\"M-H Risk Ratio Estimate: \", pooled_rr_estimate,\n    \",\\n95% Confidence Interval: (\", exp(log_CI_lower), \", \", exp(log_CI_upper), \")\", sep = \"\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nM-H Risk Ratio Estimate: 0.6009549,\n95% Confidence Interval: (0.4673707, 0.7727203)\n```\n\n\n:::\n:::\n\n\n\nOur final pooled estimate for the risk ratio is 0.60 to 2 significant figures. This is equivalent to a 40% reduction in the risk of neonatal death in premature babies whose mothers had been given antenatal steroids. \n\nTo complete our forest plot, let's add our Mantel-Haenszel estimate and its confidence interval to our forest plot. By convention, we plot the individual estimates using squares with sizes proportional to their weights, and use a diamond to distinguish our pooled estimate[^9]. \n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Creating the Final Forest Plot in R\"}\npar(mar=c(bottom=4.2, left=5.1, top=0, right=0.9), family=\"Roboto Slab\")\nempty_forest_plot(xax=c(0.1, 10), yax=c(-0.5, 8.5))\ntext(3, 0, adj=0, \"Pooled Estimate\", cex=1.2)\n\nplot_CIs(confidence_intervals)\nsegments(x0=CI[1], y0=0, \n         x1=CI[2], y1=0,\n         lwd=4.2, col=\"#009ed8\")\n\nsizes <- steroid_trials$normalised_weight*12\npoints(steroid_trials$risk_ratio, 8:1, \n       pch=15, col=\"#006a90\", cex=sizes, lwd=4.2)\npoints(steroid_trials$risk_ratio, 8:1, \n       pch=\"|\", col=\"#006a90\", cex=2.4)\npoints(pooled_rr_estimate, 0, pch=18, col=\"#006a90\", cex=12)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/forest-plot-1.png){width=1152}\n:::\n:::\n\n\n\nA meta-analysis of these eight trials, and several more completed in the intervening years, was eventually published in a systematic review in 1989[^10]. This systematic review led directly to the publication of new guidelines by the Royal College of Obstetricians and Gynaecologists in 1992, and antenatal steroids are now routinely given to mothers in premature labour[^11]. Their use is monitored, as a measure of optimal perinatal care, in the National Neonatal Audit Programme run by the Royal College of Paediatrics and Child Health[^12]. The 1989 systematic review also inspired the Cochrane Collaboration's logo -- to learn more, see [this page](https://www.cochrane.org/about-us/difference-we-make) on their website.\n\n## Further Reading\n- [**A short history of systematic reviews** -- an article by Cynthia Farquhar and Jane Marjoribanks](https://doi.org/10.1111/1471-0528.15214 )\n- [**What does the Cochrane logo tell us?** --  a presentation by Steven Woloshin](https://www.testingtreatments.org/2013/02/02/what-does-the-cochrane-logo-tell-us/)\n\n[^1]: Jane Harding and Caroline Crowther, [\"A history: antenatal corticosteroids,\"](https://www.ogmagazine.org.au/21/1-21/a-history-antenatal-corticosteroids/) *O&G Magazine* 21, no. 1 (March 2019): 13--15.\n[^2]: [\"Prenatal corticosteroids for reducing morbidity and mortality after preterm birth,\"](https://wellcomecollection.org/works/fuek3ha4) in *Wellcome Witnesses to Twentieth Century Medicine, volume 25,* edited by Tilli Tansey and Lois Reynolds. London: The Wellcome Trust Centre for the History of Medicine at UCL, 2005.\n[^3]: Patricia Crowley, [\"Prophylactic corticosteroids for preterm birth,\"](https://doi.org/10.1002/14651858.CD000065 ) *Cochrane Database of Systematic Reviews* 1996, no. 1.\n[^4]: Michael Borenstein et al., *Introduction to Meta-Analysis.* Chichester, UK: John Wiley & Sons, 2009.\n[^5]: Jeehyoung Kim, Jay Kaufman, and Heejung Bang, [\"Graphing Ratio Measures on Forest Plot,\"](https://doi.org/10.1016/j.jacc.2017.10.098) *Journal of the America College of Cardiology* 71, no. 5 (February 2018): 585--586.\n[^6]: Allan Hackshaw, *A Concise Guide to Clinical Trials.* Chichester, UK: John Wiley & Sons, 2009.\n[^7]: Julian Higgins et al., eds., [*Cochrane Handbook for Systematic Reviews of Interventions, version 6.5.*](https://training.cochrane.org/handbook) Cochrane, 2024.\n[^8]: Mathias Harrer et al., [*Doing Meta-Analysis in R: A Hands-On Guide.*](https://training.cochrane.org/handbook) Bookdown, 2021.\n[^9]: Martin Bland, *An Introduction to Medical Statistics.* 4th ed. Oxford: Oxford University Press, 2015.\n[^10]: [\"Reducing the play of chance using meta-analysis,\"](https://www.jameslindlibrary.org/essays-essay/3-3-reducing-the-play-of-chance-using-meta-analysis/) The James Lind Library, April 30, 2024.\n[^11]: Sense About Science and Academy of Medical Royal Colleges, [\"Evidence based medicine matters,\"](https://www.testingtreatments.org/2013/05/06/evidence-based-medicine-matters/) Testing Treatments interactive, May 6, 2013.\n[^12]: Audit team, [\"National Neonatal Audit Programme (NNAP) measures,\"](https://www.rcpch.ac.uk/work-we-do/clinical-audits/nnap/measures) Royal College of Paediatrics and Child Health, September 2024.",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}